all: debug_demo debug_1 debug_2 debug_3

debug_demo: debug_demo.cpp
	g++ debug_demo.cpp -o debug_demo

debug_1: debug_1.cpp
	g++ debug_1.cpp -o debug_1

debug_2: debug_2.cpp
	g++ debug_2.cpp -o debug_2

debug_3: debug_3.cpp
	g++ debug_3.cpp -o debug_3

clean:
	rm -f debug_demo debug_1 debug_2 debug_3